import type { Metadata, Viewport } from "next";
import { Public_Sans, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import AppChrome from "@/components/AppChrome";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-public-sans",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["700", "800", "900"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Airman's Playbook",
  description: "Pick your job, get the safe starting move, and go run it on GenAI.mil.",
  // The web app manifest is generated by app/manifest.ts (served at
  // /manifest.webmanifest); Next injects the <link rel="manifest"> automatically.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#003087",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} ${barlowCondensed.variable} h-full`}>
      <body className="min-h-full bg-background text-foreground font-[family-name:var(--font-public-sans)]">
        <div className="max-w-lg mx-auto min-h-screen relative">
          <div className="bg-warm text-primary-dark text-center text-[10px] font-bold uppercase tracking-widest py-1.5 px-4">
            Concept demonstration. Plays are examples, verify before official use.
          </div>
          <AppChrome />
          <main className="page-content">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
